[build]
builder = "nixpacks"
buildCommand = "npm ci --include=dev && npm run build"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/health"
port = 4000

[variables]
NODE_ENV = "development"